"""Team B developer tooling. Not imported by the service at runtime.

  python -m packages.core.devtools vectors      # -> contracts/CANONICAL_JSON_VECTORS.json
  python -m packages.core.devtools device-keys  # -> contracts/device_keys.json + dev/keys/
  python -m packages.core.devtools golden       # -> contracts/golden/S*.json (recompute hashes)
  python -m packages.core.devtools policy       # print policy_version / policy_hash
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import sys
from pathlib import Path

from .config import REPO_ROOT, settings
from .crypto.canonical import canonical_str
from .crypto.fingerprint import FINGERPRINT_FIELDS, fingerprint, preimage

CONTRACTS = REPO_ROOT / "contracts"


def _b64u(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode().rstrip("=")


# --------------------------------------------------------------------------- vectors
SAMPLE_PREIMAGE = {
    "transaction_id": "11111111-2222-3333-4444-555555555555",
    "executive_id": "EXE-001",
    "action": "TRANSFER",
    "amount_minor_units": 100000000,
    "currency": "INR",
    "beneficiary_id_or_name": "Kalyani Forge Components Pvt Ltd",
    "destination_account": "50100234874471",
    "purpose": "Q3 forging components invoice",
    "deadline_iso": "2026-09-03T18:00:00+05:30",
    "validity_window_start_iso": "2026-09-03T13:00:00+05:30",
    "validity_window_end_iso": "2026-09-03T13:15:00+05:30",
    "nonce": "n-0001",
}

SAMPLE_TOKEN = {
    "token_id": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    "transaction_id": "11111111-2222-3333-4444-555555555555",
    "transaction_fingerprint": fingerprint(SAMPLE_PREIMAGE),
    "scope": {
        "action": "TRANSFER",
        "destination_account": "50100234874471",
        "max_amount": 100000000,
        "currency": "INR",
    },
    "issued_at": "2026-09-03T13:05:00+05:30",
    "expires_at": "2026-09-03T13:10:00+05:30",
    "single_use": True,
    "policy_version": "1.0.0",
}

_CASES = [
    ("key_order_is_sorted", {"b": 2, "a": 1, "c": 3}),
    ("no_whitespace", {"a": [1, 2], "b": {"c": 1}}),
    ("null_is_sentinel_u0000", {"x": None}),
    ("empty_string_is_not_null", {"x": ""}),
    ("nfc_composed", {"payee": "Kalyanī Forge"}),
    ("nfc_decomposed_normalises_to_composed", {"payee": "Kalyanī Forge"}),
    ("non_ascii_is_not_escaped", {"cur": "₹", "hi": "पंद्रह"}),
    ("money_is_integer_minor_units", {"amount_minor_units": 250000000}),
    ("booleans_are_json_literals", {"single_use": True, "revoked": False}),
    ("array_order_is_preserved", {"steps": ["b", "a", "c"]}),
    ("nested_objects_sort_recursively", {"scope": {"z": 1, "a": {"y": 2, "b": 3}}}),
    ("negative_integers", {"delta_minor_units": -12345}),
    ("unicode_key_is_normalised", {"nāme": 1}),
]


def gen_vectors() -> Path:
    key = settings().hmac_secret.encode()
    doc = {
        "_note": (
            "Canonical-JSON conformance vectors. GENERATED by "
            "`python -m packages.core.devtools vectors` from packages/core/crypto/canonical.py. "
            "Team C MIRRORS these rules and asserts against this file; it must not import "
            "Team B code (00_SHARED_CONTEXT.md §4)."
        ),
        "rules": [
            "sort object keys lexicographically, recursively",
            "separators are ',' and ':' with no whitespace",
            "ensure_ascii = false: emit real UTF-8, never \\uXXXX for printable characters",
            "normalise every string AND every key to Unicode NFC before serialising",
            "a null value becomes the sentinel string U+0000, which JSON escapes to \\u0000",
            "money is an integer number of minor units; a float is an error, not a rounding",
            "timestamps are ISO-8601 strings with an explicit offset, never datetime objects",
            "an absent key is an error in a fingerprint pre-image; pass an explicit null",
        ],
        "hash": "sha256(utf8(canonical_string)) as lower-case hex",
        "mac": "hmac_sha256(key=INTENTLOCK_HMAC_SECRET, msg=utf8(canonical_string)) as lower-case hex",
        "cases": [
            {
                "name": name,
                "input": value,
                "canonical": canonical_str(value),
                "sha256": hashlib.sha256(canonical_str(value).encode()).hexdigest(),
            }
            for name, value in _CASES
        ],
        "rejected_inputs": [
            {"name": "float_amount", "input_repr": "{'amount': 2.5}", "expect": "TypeError"},
            {"name": "decimal_amount", "input_repr": "{'amount': Decimal('2.5')}", "expect": "TypeError"},
            {"name": "datetime_value", "input_repr": "{'at': datetime(2026,9,3)}", "expect": "TypeError"},
            {"name": "raw_bytes", "input_repr": "{'sig': b'\\x01'}", "expect": "TypeError"},
            {"name": "non_string_key", "input_repr": "{1: 'a'}", "expect": "TypeError"},
        ],
        "fingerprint": {
            "fields_in_contract_order": list(FINGERPRINT_FIELDS),
            "note": "project() requires every field to be present; the serializer then sorts.",
            "input": SAMPLE_PREIMAGE,
            "canonical": preimage(SAMPLE_PREIMAGE),
            "sha256": fingerprint(SAMPLE_PREIMAGE),
        },
        "capability_token_mac": {
            "note": (
                "MAC pre-image excludes 'mac' and 'redeemed_at'. Key below is the committed "
                "dev secret; the expected_mac only reproduces with that exact key."
            ),
            "hmac_key_used": settings().hmac_secret,
            "input": SAMPLE_TOKEN,
            "canonical": canonical_str(SAMPLE_TOKEN),
            "expected_mac": hmac.new(key, canonical_str(SAMPLE_TOKEN).encode(), hashlib.sha256).hexdigest(),
        },
    }
    out = CONTRACTS / "CANONICAL_JSON_VECTORS.json"
    out.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return out


# ----------------------------------------------------------------------- device keys
DEV_DEVICES = [
    ("DEV-EXE001-LAPTOP", "EXE-001", "active"),
    ("DEV-EXE001-PHONE", "EXE-001", "active"),
    ("DEV-EXE002-PHONE", "EXE-002", "active"),
    ("DEV-EMP101-LAPTOP", "EMP-101", "active"),
    ("DEV-EMP102-LAPTOP", "EMP-102", "active"),
    ("DEV-EMP103-PHONE", "EMP-103", "active"),
    ("DEV-EXE001-OLDPHONE", "EXE-001", "revoked"),
]


def gen_device_keys() -> Path:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import ec

    keydir = REPO_ROOT / "dev" / "keys"
    keydir.mkdir(parents=True, exist_ok=True)
    devices = []
    for device_id, owner, status in DEV_DEVICES:
        pem_path = keydir / f"{device_id}.private.pem"
        if pem_path.exists():
            priv = serialization.load_pem_private_key(pem_path.read_bytes(), password=None)
        else:
            priv = ec.generate_private_key(ec.SECP256R1())
            pem_path.write_bytes(
                priv.private_bytes(
                    serialization.Encoding.PEM,
                    serialization.PrivateFormat.PKCS8,
                    serialization.NoEncryption(),
                )
            )
            pem_path.chmod(0o600)
        spki = priv.public_key().public_bytes(
            serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo
        )
        devices.append(
            {
                "device_id": device_id,
                "owner_id": owner,
                "status": status,
                "curve": "P-256",
                "public_key_spki_b64u": _b64u(spki),
                "enrolled_at": "<TODAY-30d>",
                "family": "first_party",
            }
        )
    doc = {
        "_note": (
            "PUBLIC KEYS ONLY. Wire format is fixed by contracts/CRYPTO_WIRE_FORMAT.md: "
            "SPKI DER, base64url, no padding. Private keys live in gitignored dev/keys/ and "
            "never leave the browser in a real deployment."
        ),
        "devices": sorted(devices, key=lambda d: d["device_id"]),
    }
    out = CONTRACTS / "device_keys.json"
    out.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
    return out


def main(argv: list[str]) -> int:
    cmd = argv[1] if len(argv) > 1 else "help"
    if cmd == "vectors":
        print("wrote", gen_vectors())
    elif cmd == "device-keys":
        print("wrote", gen_device_keys())
    elif cmd == "golden":
        from .goldens import regenerate

        for p in regenerate():
            print("wrote", p)
    elif cmd == "policy":
        from .policy.version import policy_hash, policy_version

        print(f"policy_version={policy_version()} policy_hash={policy_hash()}")
    else:
        print(__doc__)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
